import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

const Nav = dynamic(() => import('main/nav'));
const Footer = dynamic(() => import('main/footer'));
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav>nav from shop</Nav>
      <main className={styles.main}>
        <h1>Shop app port 3001</h1>
      </main>
    </>
  );
}
